version: "2"

services:
    app:
        build: .
        image: example_app
        ports:
            - "8080:80"
        volumes:
            - .:/usr/src/app/
        command: "--py-autoreload=1"
